apiVersion: apps/v1 
kind: Deployment
metadata:
  name: my-awesome-deployment
spec:
  selector:
    matchLabels:
      app: my-awesome-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: my-awesome-deployment
    spec:
      containers:
        - name: my-awesome-nginx
          image: nginx
          volumeMounts:
          - mountPath: "/var/log/nginx"
            name: my-awesome-logs
      volumes:
        - name: my-awesome-logs
          persistentVolumeClaim:
            claimName: my-awesome-pvc
